(defun color-theme-tuxee ()
  "Tuxee color theme"
  (interactive)
  (color-theme-install
   '(color-theme-tuxee
     ((background-color . "#1A1A1A")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#A7A7A7")
      (foreground-color . "white")
      (mouse-color . "sienna1"))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#0C1021" :foreground "#F8F8F8"))))
     (company-tooltip ((t (:background "#242424"))))
     (company-tooltip-annotation ((t (:foreground "#888"))))
     (company-tooltip-common ((t (:foreground "#ccc"))))
     (company-tooltip-selection ((t (:background "#3c3c3c"))))
     (font-lock-builtin-face ((t (:foreground "#f2f2f2" :weight bold))))
     (font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "#6c6c6c"))))
     (font-lock-comment-face ((t (:foreground "#9e9e9e" :slant italic))))
     (font-lock-constant-face ((t (:foreground "#c8f277"))))
     (font-lock-doc-face ((t (:foreground "#84dcff"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#FF8400"))))
     (font-lock-keyword-face ((t (:foreground "#fff044"))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-string-face ((t (:foreground "#4cf"))))
     (font-lock-type-face ((t (:foreground "#ff5522"))))
     (font-lock-variable-name-face ((t (:foreground "#88E542"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     (gnus-cite-face-1 ((t (:foreground "#ad7fa8"))))
     (gnus-cite-face-2 ((t (:foreground "sienna4"))))
     (gnus-cite-face-3 ((t (:foreground "khaki4"))))
     (gnus-cite-face-4 ((t (:foreground "PaleTurquoise4"))))
     (gnus-group-mail-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "light cyan"))))
     (gnus-group-mail-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "turquoise"))))
     (gnus-group-mail-3 ((t (:foreground "white"))))
     (gnus-group-mail-3-empty ((t (:inherit gnus-group-mail-3 :foreground "#bbb"))))
     (gnus-group-mail-3-empty-face ((t (:foreground "#729fcf"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "#edd400"))))
     (gnus-group-mail-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "dodger blue"))))
     (gnus-group-news-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "light cyan"))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise"))))
     (gnus-group-news-3-empty-face ((t (:foreground "#729fcf"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "#edd400"))))
     (gnus-group-news-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "dodger blue"))))
     (gnus-header-content ((t (:italic t :foreground "#8ae234"))))
     (gnus-header-from ((t (:bold t :foreground "#edd400"))))
     (gnus-header-name-face ((t (:bold t :foreground "#729fcf"))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3"))))
     (gnus-header-subject ((t (:foreground "#edd400"))))
     (gnus-signature-face ((t (:italic t :foreground "dark grey"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "rotal blue"))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "lime green"))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "tomato"))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "white"))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "lime green"))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "royal blue"))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "dark red"))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "white"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "royal blue"))))
     (gnus-summary-normal-read-face ((t (:foreground "lime green"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "indian red"))))
     (gnus-summary-normal-unread-face ((t (:foreground "white"))))
     (gnus-summary-selected ((t (:background "brown4" :foreground "white"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (highlight ((t (:background "#222222"))))
     (highline-face ((t (:background "SeaGreen"))))
     (isearch ((t (:background "#162" :foreground "white"))))
     (italic ((t (nil))))
     (lazy-highlight ((t (:inherit isearch :foreground "#cec"))))
     (left-margin ((t (nil))))
     (linum ((t (:background "#2c2c2c" :foreground "#555"))))
     (lsp-face-highlight-textual ((t (:foreground "#f20" :weight bold))))
     (lsp-face-highlight-write ((t (:background "#005511" :foreground "white"))))
     (lsp-ui-doc-background ((t (:background "black"))))
     (lsp-ui-doc-header ((t (:background "#cccccc" :foreground "black" :weight bold))))
     (magit-blame-highlight ((t (:background "#333" :foreground "#aaa"))))
     (magit-diff-added ((t (:foreground "#af8"))))
     (magit-diff-added-highlight ((t (:inherit (magit-diff-added magit-diff-context-highlight)))))
     (magit-diff-context ((t nil)))
     (magit-diff-context-highlight ((t (:background "#242424"))))
     (magit-diff-hunk-heading ((t (:background "#333" :foreground "grey70"))))
     (magit-diff-hunk-heading-highlight ((t (:background "#444" :foreground "white"))))
     (magit-diff-removed ((t (:foreground "#f55"))))
     (magit-diff-removed-highlight ((t (:inherit (magit-diff-removed magit-diff-context-highlight)))))
     (markdown-code-face ((t nil)))
     (message-cited-text ((t (:foreground "#edd400"))))
     (message-header-cc ((t (:foreground "white"))))
     (message-header-name-face ((t (:foreground "tomato"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3"))))
     (message-header-other-face ((t (:foreground "LightSkyBlue3"))))
     (message-header-subject ((t (:foreground "white"))))
     (message-header-to ((t (:foreground "white"))))
     (message-header-xheader-face ((t (:foreground "DodgerBlue3"))))
     (mode-line ((t (:background "grey75" :foreground "grey10"))))
     (mode-line-inactive ((t (:inherit mode-line :background "grey40" :foreground "black" :weight light))))
     (neo-dir-link-face ((t (:foreground "#4cf"))))
     (org-agenda-date ((t (:foreground "#6ac214"))))
     (org-agenda-date-today ((t (:weight bold :foreground "#edd400"))))
     (org-agenda-date-weekend ((t (:weight normal :foreground "dodger blue"))))
     (org-agenda-structure ((t (:weight bold :foreground "tomato"))))
     (org-block ((t (:foreground "#bbbbbc"))))
     (org-date ((t (:underline t :foreground "magenta3"))))
     (org-done ((t (:bold t :foreground "ForestGreen"))))
     (org-footnote  ((t (:underline t :foreground "magenta3"))))
     (org-hide ((t (:foreground "#2e3436"))))
     (org-level-1 ((t (:bold t :foreground "dodger blue" :height 1.5))))
     (org-level-2 ((t (:bold nil :foreground "#edd400" :height 1.2))))
     (org-level-3 ((t (:bold t :foreground "#6ac214" :height 1.0))))
     (org-level-4 ((t (:bold nil :foreground "tomato" :height 1.0))))
     (org-link ((t (:foreground "skyblue2" :background "#2e3436"))))
     (org-quote ((t (:inherit org-block :slant italic))))
     (org-special-keyword ((t (:foreground "brown"))))
     (org-todo ((t (:bold t :foreground "Red"))))
     (org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
     (org-verse ((t (:inherit org-block :slant italic))))
     (region ((t (:background "#253B76"))))
     (shadow ((t (:foreground "grey40"))))
     (smerge-refined-added ((t (:inherit smerge-refined-change :background "#228822"))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (toolbar ((t (nil))))
     (underline ((nil (:underline nil))))
     (window-divider ((t (:foreground "black"))))
     (window-divider-first-pixel ((t (:foreground "black"))))
     (window-divider-last-pixel ((t (:foreground "black"))))
     (zmacs-region ((t (:background "snow" :foreground "ble"))))
     )))

;(provide 'color-theme-tuxee)
